### ISSUE TITLE
.idea files commited

### ISSUE THREAD

**Issue by lasote** [jfrogtraining/swampup#1]
Hi Stanley,

I'm Luis from Conan, it's intended to upload the ".idea" directory? My IDE is going crazy with it.

Thanks!

**Comment by lasote** [comment]
In the "sample" folder there is another .idea folder.

**Comment by stanlef** [comment]
I try not to commit the .idea folder - the sample folder will be replaced and I will make sure the .idea folder will not get uploaded. 

stanley

**Comment by stanlef** [comment]
Closing the issue now.  .idea folder is not commited.
